name: Publish Python distribution to PyPI

on:
  release:
    types:
    - published
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:

    # Only run the job for releases and PRs against main from release* branches
    if: >-
      github.event_name == 'release' ||
      (github.event_name == 'pull_request' && startswith(github.head_ref, 'release'))

    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install build
      run: >-
        python -m
        pip install
        build typing-extensions
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution to PyPI
      # Publish to PyPi for releases
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}

    - name: Check for test package
      id: check-test-pypi
      if: github.event_name == 'pull_request'
      run: >-
        pip install -e .;
        MLHUB_VERSION=$(python -c "import radiant_mlhub; print(radiant_mlhub.__version__)");
        CURL_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://test.pypi.org/project/radiant-mlhub/${MLHUB_VERSION}/);
        if [ ${CURL_STATUS_CODE} -eq 200 ]; then PACKAGE_EXISTS="True"; else PACKAGE_EXISTS="False"; fi;
        echo "::set-output name=package_exists::${PACKAGE_EXISTS}";

    - name: Publish distribution to TestPyPI
      # Publish to TestPyPi for PRs against main from release branches
      if: github.event_name == 'pull_request' && steps.check-test-pypi.outputs.package_exists != 'True'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
