name: Unit tests live vs. staging API

on:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * SUN'

jobs:

  test_vs_staging_api:

    strategy:
      matrix:
        python-version:
          - "3.11"
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements_testing.txt

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_testing.txt
      - name: Run tests
        env:
          MLHUB_API_KEY: ${{ secrets.mlhub_api_key_staging }}
          MLHUB_CI: 'true'
        run: |
          pip install .
          pytest --record-mode=rewrite
